### ISSUE TITLE
Add new Image Effects

### ISSUE THREAD

**Issue by imniladri** [imniladri/Miscellaneous#12]
Add some new image effects for websites.
- Here is the project directory `./Miscellaneous/Hover-Effects/Image-Hover-Effects/`
- See the other folder structure to maintain yours.

**Comment by Shubh942** [comment]
@imniladri Please assign me this issue. I'm very interested in doing this type of task

**Comment by diviprakashpc** [comment]
Can I take up this issue? I am thinking to add more hover effects like unblur effect or the black n white effect.

**Comment by imniladri** [comment]
> Can I take up this issue? I am thinking to add more hover effects like unblur effect or the black n white effect.

Great! Go for it. Just make folders named `Image-Hover-Effect-{5}` etc. in this directory [`./Miscellaneous/Hover-Effects/Image-Hover-Effects/`](https://github.com/imniladri/Miscellaneous/tree/main/Hover-Effects/Image-Hover-Effects) and start working on it.
Also, see the other image effects folder structure to maintain yours.
And you're requested to make a branch named `new-image-effect`.

**Comment by Eazyisreal** [comment]
@imniladri Kindly Assign this task to me
