### ISSUE TITLE
Add new Button Hover Effects

### ISSUE THREAD

**Issue by imniladri** [imniladri/Miscellaneous#20]
Add some new button hover effects but simple not complex.
- Here is the project directory `./Miscellaneous/Hover-Effects/Button-Hover-Effects/`
- See the other folder structure to maintain yours.

**Comment by Eazyisreal** [comment]
@imniladri Kindly assign this issue to me

**Comment by Adish90k** [comment]
can you assign it to me?

**Comment by ankitkumar0622** [comment]
hi ,can you assign this to me

**Comment by imniladri** [comment]
Assigning all!
Here is your **_working directory list_** and **_branch name list_**.
1. @Eazyisreal: 
     Directory: [`./Miscellaneous/Hover-Effects/Button-Hover-Effects/Button-Hover-Effect-3`](https://github.com/imniladri/Miscellaneous/tree/main/Hover-Effects/Button-Hover-Effects/Button-Hover-Effect-3)
     Branch Name: `{new-button-effect-3}`

2. @Adish90k:
    Directory: [`./Miscellaneous/Hover-Effects/Button-Hover-Effects/Button-Hover-Effect-4`](https://github.com/imniladri/Miscellaneous/tree/main/Hover-Effects/Button-Hover-Effects/Button-Hover-Effect-4)
     Branch Name: `{new-button-effect-4}` 

3. @ankitkumar0622:
    Directory: [`./Miscellaneous/Hover-Effects/Button-Hover-Effects/Button-Hover-Effect-5`](https://github.com/imniladri/Miscellaneous/tree/main/Hover-Effects/Button-Hover-Effects/Button-Hover-Effect-5)
     Branch Name: `{new-button-effect-5}` 

NB: **Make your branch separately as mentioned above.**
CC: @Eazyisreal @Adish90k @ankitkumar0622 

All the best!

**Comment by ankitkumar0622** [comment]
@imniladri , i have added a new button with hover effect and made a pull request can you please have a look, my pr number is #22

**Comment by Adish90k** [comment]
@imniladri i have made a pull request canbyou please check it out?

**Comment by Eazyisreal** [comment]
@imniladri Kindly check my PR #25
