### ISSUE TITLE
Add new Card Hover Effects

### ISSUE THREAD

**Issue by imniladri** [imniladri/Miscellaneous#7]
Add some new card hover effects.
- Here is the project directory `./Miscellaneous/Hover-Effects/Card-Hover-Effects/`
- See the other folder structure to maintain yours.

**Comment by joanjeremiah** [comment]
I would like to solve this issue. Kindly assign this to me.

**Comment by imniladri** [comment]
> I would like to solve this issue. Kindly assign this to me.

Go for it. @joanjeremiah

**Comment by Sourajeet-Dey** [comment]
I like add new card hover effects. Please assign me.

**Comment by Eazyisreal** [comment]
@imniladri Kindly assign this task to me
